### ISSUE TITLE
error exeption

### ISSUE THREAD

**Issue by EstuDev** [gheav/CodeIgniter4-AdminPanel#3]
str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated

`<div class="col-12 col-lg-8 col-xxl-8 d-flex">
 92         <div class="card border flex-fill">
 93             <div class="card-header mb-0">
 94                 <h5 class="card-title "> Source Code </h5>
 95             </div>
 96             <div class="card-body">
 97                 <?php
 98                 $functionName   = str_replace(' ', '', ucwords(strtolower(str_replace('_', ' ', $tableName))));
 99                 $modelName      = str_replace(' ', '', ucwords(strtolower(str_replace('_', ' ', $menu))));
100                 $title          = ucwords(strtolower(str_replace('_', ' ', $menu)));
101 
102                 ?>
103 
104                 <?php if ($file == 'controller') : ?>
105                     <h5 class="fw-bold"> Constructor</h5>`

**Comment by gilangheavy** [comment]
what version of php are you using?

**Comment by EstuDev** [comment]
Php 7

Pada tanggal Jum, 8 Jul 2022 19.07, Gilang Heavy ***@***.***>
menulis:

**Comment by EstuDev** [comment]
Mohon maaf ternyata saya salah pilih versi lho
Untuk user pass login apa pak


Pada tanggal Jum, 8 Jul 2022 22.43, WAHYU ROHMANTO <
***@***.***> menulis:

**Comment by gilangheavy** [comment]
Bisa di cek di database migrasi

**Comment by EstuDev** [comment]
Siap

Pada tanggal Sab, 9 Jul 2022 17.02, Gilang Heavy ***@***.***>
menulis:

**Comment by EstuDev** [comment]
Maaf pak sudah saya coba nemu error seperti ini
Bagaimana cara memperbaikinya


Terimakasih sebelumnya

Pada tanggal Sab, 9 Jul 2022 19.28, WAHYU ROHMANTO <
***@***.***> menulis:

**Comment by EstuDev** [comment]
Mohon maaf yang tadi sudah ketemu pak ganti nemu error lagi

Saya pakai php 8,1

**Comment by gilangheavy** [comment]
disarankan menggunakan php versi 8.0
