### ISSUE TITLE
Table 'adminci4.user_submenu_category' doesn't exist 

### ISSUE THREAD

**Issue by treborin** [gheav/CodeIgniter4-AdminPanel#4]
First, thanks for this clever starter panel. Easy and very usefull.
Btw, i updated CI4 up to ver. 4.2.3 with composer and it's working fine.

Error when creting a submenu. It seems that table user_submenu_category is not inside seeds folder.

**Comment by gilangheavy** [comment]
thanks for the correction, indeed we do not provide examples for submenus
