### ISSUE TITLE
Suggested enhancement to the ci4_admin_panel source by byoosdigital.com

### ISSUE THREAD

**Issue by DEV-byoos** [gheav/CodeIgniter4-AdminPanel#6]
hello dev's
config:  PHP 8.2 -  CI4.3.1  -  debian 11.6

## correctifs  byoosdigital.com
IN /root/app/Config/Exceptions.php

	// byoosdigital.com
    public $sensitiveDataInTrace;
    public $logDeprecations;
    public $deprecationLogLevel;        

IN /root/app/Controllers/BaseController.php

	// byoosdigital.com
	protected $session;
	protected $segment;
	protected $db;
	protected $validation;
	protected $encrypter;
	protected $menuModel;

IN /root/app/Controllers/Welcome.php

FILTER_SANITIZE_STRING is deprecated, what to use instead?
htmlspecialchars($this->request->getVar('inputEmail', FILTER_UNSAFE_RAW));

IN /root/App/Filters/Authorization.php
Creation of dynamic property App\Filters\Authorization::$userModel is deprecated
class Authorization implements FilterInterface
{
	// byoosdigital.com
	protected $userModel;
	protected $menuModel;	

IN /root/App/Filters/CRUDGenerator.php
class CRUDGenerator extends BaseController
{
	// byoosdigital.com
	protected $developerModel;

AND
IN /root/app/Databnase/Migrations/2021-05-20-124435_Session.php
replace  		$this->forge->addKey('ip_address', true);
to
		$this->forge->addKey('timestamp', true);

best regards

**Comment by gilangheavy** [comment]
hai DEV-byoos, thanks for the advice, we will make adjustments to the source code soon as we are currently working on another project.
